services:
  nginx:
    container_name: tasks-nginx
    build:
      context: .docker/nginx
    ports:
      - "443:443"
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d
      - ./:/code
    working_dir: /code
    depends_on:
      - php-fpm

  php-fpm:
    container_name: tasks-php-fpm
    build:
      context: .docker/php-fpm
    working_dir: /code
    volumes:
      - ./:/code

  database:
    container_name: tasks-mysql
    build:
      context: .docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=tasks
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"

volumes:
  database_data:
